### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by JonathanAaron** [uzyn/tag#10]
[Enter steps to reproduce below:]
I was just closing at <link> tag with </link> and this just popped up. (I'm working in a yeoman angular generator.)
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tag](https://github.com/uzyn/tag) package, v0.2.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:128

TypeError: undefined is not a function
  at getTag (/Users/jsandusky/.atom/packages/tag/lib/tag.js:79:42)
  at Object.module.exports.getClosingTag (/Users/jsandusky/.atom/packages/tag/lib/tag.js:112:17)
  at Object.module.exports.bufferChanged (/Users/jsandusky/.atom/packages/tag/lib/tag.js:59:27)
  at /Users/jsandusky/.atom/packages/tag/lib/tag.js:13:17
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:605:12)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:515:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:464:43)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:808:31
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:848:29
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:697:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1211:26)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:842:24
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2131:18)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:840:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:805:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:423:31
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:697:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1211:26)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:421:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:61)

```

### Commands

```
     -1:07.1 editor:newline (atom-text-editor.editor.is-focused)
     -1:06.8 core:paste (atom-text-editor.editor.is-focused)
  2x -0:29.6 core:undo (atom-text-editor.editor.is-focused)
     -0:18.9 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:17.6 core:move-down (atom-text-editor.editor.is-focused)
     -0:16.4 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:13.6 core:move-left (atom-text-editor.editor.is-focused)
 13x -0:13.3 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.9 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:07.1 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.2 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.8 core:move-right (atom-text-editor.editor.is-focused)
     -0:03.3 core:move-left (atom-text-editor.editor.is-focused)
     -0:02.3 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.9 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-status",
      "cut-line",
      "wrap-guide",
      "linter",
      "autocomplete",
      "SFTP-deployment"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.3
autoclose-html, v0.15.0
ide-haskell, v0.3.1
language-haskell, v1.0.0
language-scala, v1.1.0
linter-jshint, v0.1.0
seti-syntax, v0.3.1
seti-ui, v0.6.3
tag, v0.2.3

# Dev
No dev packages
```

**Comment by uzyn** [comment]
This issue should be fixed now with v0.3.0.

Please update.
