### ISSUE TITLE
Failed to activate the tag package

### ISSUE THREAD

**Issue by tellowkrinkle** [uzyn/tag#11]
[Enter steps to reproduce below:]

1. Click install button
2. Fail

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.4
**Thrown From**: [tag](https://github.com/uzyn/tag) package, v0.2.3

### Stack Trace

Failed to activate the tag package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
  at Object.module.exports.activate (/Users/evan/.atom/packages/tag/lib/tag.js:11:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:303:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:132:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:213:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -1:30.7.0 application:new-file (atom-text-editor.editor)
     -1:29.9.0 core:save (atom-text-editor.editor)
 10x -1:19 core:backspace (atom-text-editor.editor)
  3x -1:11.9.0 editor:newline (atom-text-editor.editor)
     -0:52.2.0 settings-view:open (atom-text-editor.editor)
  2x -0:48.2.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
indentation-indicator, v0.4.1
minimap, v4.7.6
tag, v0.2.3

# Dev
No dev packages
```

**Comment by uzyn** [comment]
This issue should be fixed now with v0.3.0.

Please update.
